steps:
  - id: 'ssh into GCE instance'
    name: gcr.io/cloud-builders/gcloud
    args: [
      'compute',
      'ssh',
      '--zone',
      'us-central1-a',
      'portfolio',
      '--',
      'cd ../chinkinma_gmail_com/personal-website-docker-compose && sudo docker-compose down && sudo git pull && cd .. && sudo docker-compose -f ../personal-website-docker-compose/docker-compose.yaml up -d && sudo docker ps'
    ]