# git stash is required during ssh because the automated ssl certification script makes small changes

steps:
  - id: 'ssh into GCE instance'
    name: gcr.io/cloud-builders/gcloud
    args: [
      'compute',
      'ssh',
      '--zone',
      'us-central1-a',
      'portfolio',
      '--',
      'cd ../chinkinma_gmail_com/personal-website-docker-compose',
      '&& sudo docker-compose down',
      '&& sudo git stash',
      '&& sudo git pull',
      '&& sudo chmod +x init-letsencrypt.sh',
      '&& cd ..',
      '&& sudo docker-compose -f personal-website-docker-compose/docker-compose.yaml up -d',
      '&& sudo docker ps'
    ]