# git stash is required during ssh because the automated ssl certification script makes small changes

steps:
  - id: 'delete old cloudbuild ssh keys to keep profile json under 32kb limit'
    name: gcr.io/cloud-builders/gcloud
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      for i in $(gcloud compute os-login ssh-keys list | grep -v FINGERPRINT); do echo $i; gcloud compute os-login ssh-keys remove --key $i; done
  
  - id: 'ssh into GCE instance'
    name: gcr.io/cloud-builders/gcloud
    args: [
      'compute',
      'ssh',
      '--zone',
      'us-central1-a',
      'portfolio',
      '--',
      'cd ../chinkinma_gmail_com/personal-website-docker-compose',
      '&& sudo docker-compose down',
      '&& sudo git stash',
      '&& sudo git pull',
      '&& sudo chmod +x init-letsencrypt.sh',
      '&& cd ..',
      '&& sudo docker-compose -f personal-website-docker-compose/docker-compose.yaml up -d',
      '&& sudo docker ps'
    ]