version: '3.6'
services:
  nginx:
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  homepage:
    image: gcr.io/portfolio-252919/personal-website-homepage
    restart: always
    depends_on:
      - nginx

  baseapp:
    image: gcr.io/portfolio-252919/personal-website-base-app
    restart: always
    depends_on:
      - nginx
