version: '3.6'
services:
  nginx:
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:80

  homepage:
    image: homepage
    restart: always
    depends_on:
      - nginx

  baseapp:
    image: baseapp
    restart: always
    depends_on:
      - nginx
