version: '3.6'
services:
  nginx:
    image: nginx:1.17-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:v0.36.0
    restart: unless-stopped
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  homepage:
    image: gcr.io/portfolio-252919/personal-website-homepage
    restart: always
    depends_on:
      - nginx

  baseapp:
    image: gcr.io/portfolio-252919/personal-website-base-app
    restart: always
    depends_on:
      - nginx
